-- GRADE SERVICE (grade_db)
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('13', '80', 7.86, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('9', '73', 13.89, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('43', '93', 7.91, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('119', '19', 12.56, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('95', '49', 9.55, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('67', '96', 16.75, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('58', '94', 9.68, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('56', '83', 18.92, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('86', '74', 17.58, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('112', '23', 10.52, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('49', '4', 11.99, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('52', '98', 12.32, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('63', '2', 9.39, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('87', '42', 11.23, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('98', '32', 11.79, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('45', '96', 16.67, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('83', '5', 17.06, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('38', '96', 12.95, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('5', '86', 18.29, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('11', '69', 12.81, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('30', '9', 18.85, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('63', '8', 13.39, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('43', '94', 10.54, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('41', '19', 8.35, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('98', '60', 19.47, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('12', '53', 7.95, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('45', '89', 7.24, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('68', '19', 12.09, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('51', '31', 7.58, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('52', '54', 10.81, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('106', '95', 8.11, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('64', '44', 9.74, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('9', '39', 17.67, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('101', '10', 16.07, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('36', '26', 16.06, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('55', '19', 19.03, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('114', '86', 17.02, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('23', '2', 16.34, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('17', '10', 14.31, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('45', '51', 9.58, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('53', '19', 16.23, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('11', '27', 16.07, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('81', '95', 16.16, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('6', '84', 12.73, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('30', '80', 7.03, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('6', '12', 18.54, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('50', '24', 14.16, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('49', '55', 7.97, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('91', '93', 13.05, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('60', '11', 18.82, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('82', '88', 14.24, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('118', '90', 10.77, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('69', '83', 11.69, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('41', '11', 17.91, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('3', '53', 11.41, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('57', '68', 12.26, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('22', '100', 7.88, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('63', '90', 16.66, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('24', '39', 18.21, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('24', '29', 18.58, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('33', '46', 11.77, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('20', '84', 10.44, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('39', '94', 18.03, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('56', '25', 12.78, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('75', '88', 9.79, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('91', '87', 13.97, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('63', '2', 18.7, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('71', '55', 14.91, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('71', '69', 16.21, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('111', '38', 12.6, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('107', '46', 19.45, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('52', '85', 16.95, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('42', '31', 11.57, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('48', '19', 8.26, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('27', '26', 10.61, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('113', '41', 13.74, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('15', '85', 12.74, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('80', '86', 10.8, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('75', '17', 16.61, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('55', '83', 15.67, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('121', '54', 10.85, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('116', '58', 17.56, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('84', '28', 7.94, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('41', '84', 8.37, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('4', '79', 9.67, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('85', '72', 12.95, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('93', '33', 12.69, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('32', '51', 18.77, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('93', '66', 14.18, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('106', '32', 9.67, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('107', '95', 14.72, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('64', '24', 12.41, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('75', '23', 16.17, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('48', '6', 11.15, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('81', '78', 13.51, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('28', '89', 18.88, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('40', '95', 11.62, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('5', '10', 19.35, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('6', '77', 17.54, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('49', '54', 8.5, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('49', '68', 12.06, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('115', '26', 10.57, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('118', '85', 12.47, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('63', '7', 9.48, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('68', '40', 7.43, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('39', '68', 8.88, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('57', '59', 17.84, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('114', '24', 18.81, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('66', '48', 17.72, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('31', '36', 17.21, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('18', '39', 19.02, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('86', '52', 10.58, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('5', '28', 15.07, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('99', '86', 14.9, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('12', '85', 8.09, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('58', '79', 12.17, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('44', '87', 11.7, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('99', '29', 14.79, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('103', '52', 14.37, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('5', '26', 8.63, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('13', '60', 18.36, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('112', '35', 11.53, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('81', '74', 14.09, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('46', '47', 14.49, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('77', '36', 7.43, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('98', '1', 13.8, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('77', '59', 16.28, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('70', '83', 7.43, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('118', '65', 14.14, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('29', '72', 16.09, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('66', '66', 10.13, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('74', '24', 7.96, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('106', '99', 9.87, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('107', '26', 19.26, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('8', '73', 12.7, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('56', '74', 9.38, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('80', '99', 18.08, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('60', '91', 16.66, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('68', '68', 16.05, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('68', '94', 17.87, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('49', '99', 8.92, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('17', '61', 16.1, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('106', '5', 18.79, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('81', '37', 15.0, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('21', '40', 9.68, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('7', '98', 13.99, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('52', '32', 12.11, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('4', '25', 7.68, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('27', '65', 13.19, 'FINAL', 'Note validée', NOW());
INSERT INTO grades (student_id, course_id, grade, grade_type, feedback, created_at) VALUES ('15', '100', 15.19, 'FINAL', 'Note validée', NOW());
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('63', '29', '2024-11-10', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('14', '25', '2024-11-13', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('10', '90', '2024-11-20', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('20', '58', '2024-11-14', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('98', '65', '2024-11-15', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('37', '32', '2024-11-05', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('14', '37', '2024-11-14', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('90', '12', '2024-11-13', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('43', '66', '2024-11-07', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('52', '8', '2024-11-06', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('28', '12', '2024-11-03', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('73', '60', '2024-11-12', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('44', '22', '2024-11-23', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('89', '90', '2024-11-23', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('77', '20', '2024-11-16', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('110', '29', '2024-11-01', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('60', '73', '2024-11-24', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('25', '83', '2024-11-11', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('103', '54', '2024-11-28', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('76', '44', '2024-11-19', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('43', '40', '2024-11-28', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('96', '83', '2024-11-01', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('59', '40', '2024-11-25', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('96', '39', '2024-11-01', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('66', '87', '2024-11-21', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('78', '67', '2024-11-12', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('73', '30', '2024-11-01', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('72', '1', '2024-11-24', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('60', '23', '2024-11-19', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('93', '60', '2024-11-01', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('26', '85', '2024-11-25', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('64', '97', '2024-11-19', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('97', '39', '2024-11-17', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('59', '6', '2024-11-19', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('77', '37', '2024-11-15', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('13', '97', '2024-11-07', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('2', '31', '2024-11-24', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('41', '87', '2024-11-19', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('16', '62', '2024-11-15', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('48', '14', '2024-11-01', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('75', '17', '2024-11-13', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('30', '3', '2024-11-10', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('3', '79', '2024-11-05', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('67', '34', '2024-11-27', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('65', '91', '2024-11-24', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('119', '1', '2024-11-26', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('49', '54', '2024-11-27', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('21', '80', '2024-11-07', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('79', '98', '2024-11-22', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('96', '59', '2024-11-10', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('52', '76', '2024-11-17', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('109', '96', '2024-11-07', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('4', '37', '2024-11-04', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('56', '33', '2024-11-19', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('36', '47', '2024-11-28', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('46', '46', '2024-11-24', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('16', '23', '2024-11-15', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('121', '71', '2024-11-17', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('118', '24', '2024-11-13', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('15', '83', '2024-11-14', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('29', '32', '2024-11-08', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('111', '82', '2024-11-25', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('50', '26', '2024-11-14', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('102', '34', '2024-11-10', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('17', '50', '2024-11-26', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('55', '44', '2024-11-08', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('113', '13', '2024-11-10', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('89', '36', '2024-11-12', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('66', '76', '2024-11-24', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('58', '20', '2024-11-15', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('83', '59', '2024-11-24', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('37', '100', '2024-11-02', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('47', '25', '2024-11-09', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('76', '71', '2024-11-05', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('26', '55', '2024-11-22', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('91', '3', '2024-11-17', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('121', '42', '2024-11-16', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('27', '50', '2024-11-04', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('19', '86', '2024-11-18', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('66', '89', '2024-11-20', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('82', '50', '2024-11-01', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('118', '41', '2024-11-11', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('97', '23', '2024-11-08', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('107', '34', '2024-11-05', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('39', '75', '2024-11-04', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('54', '96', '2024-11-13', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('121', '46', '2024-11-23', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('117', '80', '2024-11-09', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('111', '53', '2024-11-02', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('94', '8', '2024-11-06', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('12', '43', '2024-11-03', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('43', '28', '2024-11-19', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('24', '45', '2024-11-08', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('120', '96', '2024-11-13', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('65', '68', '2024-11-25', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('67', '81', '2024-11-25', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('42', '18', '2024-11-21', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('110', '29', '2024-11-12', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('37', '96', '2024-11-16', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('63', '40', '2024-11-14', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('104', '91', '2024-11-28', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('54', '25', '2024-11-02', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('114', '61', '2024-11-01', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('110', '40', '2024-11-07', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('11', '88', '2024-11-19', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('92', '93', '2024-11-26', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('61', '63', '2024-11-17', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('119', '30', '2024-11-09', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('21', '36', '2024-11-25', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('4', '99', '2024-11-19', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('83', '6', '2024-11-04', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('56', '90', '2024-11-16', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('32', '4', '2024-11-25', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('119', '58', '2024-11-02', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('50', '4', '2024-11-22', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('66', '76', '2024-11-10', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('45', '81', '2024-11-10', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('70', '9', '2024-11-16', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('90', '47', '2024-11-04', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('108', '78', '2024-11-27', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('41', '92', '2024-11-19', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('56', '35', '2024-11-25', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('4', '10', '2024-11-03', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('114', '19', '2024-11-09', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('74', '76', '2024-11-13', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('93', '47', '2024-11-12', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('108', '40', '2024-11-27', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('82', '35', '2024-11-03', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('110', '96', '2024-11-09', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('35', '27', '2024-11-15', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('66', '66', '2024-11-15', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('69', '27', '2024-11-13', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('99', '58', '2024-11-26', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('26', '53', '2024-11-17', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('40', '91', '2024-11-26', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('56', '87', '2024-11-04', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('89', '97', '2024-11-26', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('40', '7', '2024-11-05', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('50', '26', '2024-11-16', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('74', '34', '2024-11-09', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('60', '52', '2024-11-17', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('55', '40', '2024-11-25', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('20', '32', '2024-11-13', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('13', '75', '2024-11-17', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('106', '24', '2024-11-07', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('100', '35', '2024-11-15', 'ABSENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('67', '38', '2024-11-05', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('78', '83', '2024-11-13', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('30', '28', '2024-11-21', 'PRESENT', '');
INSERT INTO attendance (student_id, course_id, session_date, status, remarks) VALUES ('43', '54', '2024-11-24', 'PRESENT', '');